[dev]
    command = "yarn dev"
    framework = "#custom"
    targetPort = 3000

[build]
  command = "CI='' npm run build"
  publish = "/build"
  base ="/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
